# v0.3
before_script:
  - echo "echo before run script"

stages:
  - deploy_webtest
  - deploy_prod

deploy_webtest:
  stage: deploy_webtest
  only:
    - webtest
  script:
    - echo "RUN build_deploy script"
    # Переходим в папку репозиторя на проде
    - cd /home/$USER_DEPLOY/web/dev-$CI_PROJECT_NAME/public_html
    # First  run
    #  - git init . && git remote add origin $CI_REPOSITORY_URL && git pull origin webtest
    # Always run
    - git pull origin webtest
    - echo "Ok pull"
    # Composer  install
    - composer install
    # Config import
    - drush cim
    # Cache rebuild
    - drush cr
    # Database update
    - drush updb -y

deploy_prod:
  stage: deploy_prod
  only:
    - master
  script:
    - echo "RUN build_deploy script"
    # Переходим в папку репозиторя на проде
    - cd /home/$USER_DEPLOY/web/$CI_PROJECT_NAME/public_html
    - git pull origin master
    - echo "Ok pull"
    # Composer install
    - composer install --no-dev
    # Database update
    - drush updb -y
    # Config import
    - drush cim
    # Cache rebuild
    - drush cr

