
before_script:
  - echo "This job tests something"

stages:
  - build_deploy

build_deploy:
  stage: build_deploy
  only:
    - master
  script:
    - echo "RUN build_deploy script"
    # Переходим в папку репозиторя на проде
    - cd /home/$USER_DEPLOY/web/$CI_PROJECT_NAME/public_html
    - git pull origin master
    - echo "Ok pull"
    # Composer install And drush cr
    - composer install --no-dev
    # echo "Composer install Success"
    - drush updb
    # echo "Database update Success"
    - drush cim
    # echo "Configurate import Success"
    - drush cr
