# v0.3
before_script:
  - echo "This job tests something"

stages:
  - build_deploy

build_deploy:
  stage: build_deploy
  only:
    - master
  script:
    - echo "RUN build_deploy script"
    # Переходим в папку репозиторя на проде
    - cd /home/$USER_DEPLOY/web/$CI_PROJECT_NAME/public_html
    - git pull origin master
    - echo "Ok pull"
    # Composer install
    - composer install --no-dev
    # Config import
    - drush cim
    # Database update
    - drush updb -y
    # Cache rebuild
    - drush cr

